version: '2'
services:
  daemon:
    build: .
    image: kresten/skycave
    command: daemon -Dcpf=mongo-storage-compose.cpf
    #expose the daemon on port 37123
    ports:
    - "37123:37123"
    #links the daemon to the mongo db, so mongo is created before the daemon.
    depends_on:
    - mongo
  mongo:
    image: mongo:3.3.15
    container_name: mongo
    #use following commands, so the database does not use up too much space.
    #The database is already exposed on port 27017 by default, so no port commands are necessary
    command: --smallfiles --noprealloc

