version: '2'
services:
  daemon:
    #build image from Dockerfile
    build: .
    image: kresten/skycave
    #run the image with daemon command and latest.cpf
    command: daemon -Dcpf=mongo-storage-compose.cpf
    #expose the daemon on port 37123
    ports:
    - "37123:37123"
    #links the daemon to the mongo db, so mongo is created before the daemon.
    depends_on:
    - mongo
  mongo:
    #use latest mongo image
    image: mongo
    container_name: mongo
    #use smallfiles and noprealloc commands. The database is already exposed on port 27017 by default
    command: --smallfiles --noprealloc

