version: '2'
services:
  mongors1:
    image: aupts2/mongodb:latest
    command: mongod --noprealloc --smallfiles --replSet rs1 --port 27018
    container_name: mongors1
    hostname: mongors1
    ports:
    - "27018:27018"
  mongors2:
    image: aupts2/mongodb:latest
    command: mongod --noprealloc --smallfiles --replSet rs1 --port 27019
    container_name: mongors2
    hostname: mongors2
    ports:
    - "27019:27019"
  mongors3:
    image: aupts2/mongodb:latest
    command: mongod --noprealloc --smallfiles --replSet rs1 --port 27020
    container_name: mongors3
    hostname: mongors3
    ports:
    - "27020:27020"
  mongocfg1:
    image: aupts2/mongodb:latest
    command: mongod --noprealloc --smallfiles --configsvr --port 27021
    container_name: mongocfg1
    hostname: mongocfg1
    ports:
    - "27021:27021"
  mongocfg2:
    image: aupts2/mongodb:latest
    command: mongod --noprealloc --smallfiles --configsvr --port 27022
    container_name: mongocfg2
    hostname: mongocfg2
    ports:
    - "27022:27022"
  mongocfg3:
    image: aupts2/mongodb:latest
    command: mongod --noprealloc --smallfiles --configsvr --noauth --port 27023
    container_name: mongocfg3
    hostname: mongocfg3
    ports:
    - "27023:27023"
  mongos1:
    image: aupts2/mongodb:latest
    command: mongos --configdb mongocfg1:27021,mongocfg2:27022,mongocfg3:27023 --port 27017
    container_name: mongos1
    hostname: mongos1
    ports:
    - "27017:27017"