version: '2'
services:
  mongors1:
    image: aupts2/mongodb:latest
    command: mongod --noprealloc --smallfiles --replSet rs1 --nojournal --oplogSize 16 --noauth --port 27017
    container_name: mongors1
  mongors2:
    image: aupts2/mongodb:latest
    command: mongod --noprealloc --smallfiles --replSet rs1 --nojournal --oplogSize 16 --noauth --port 27017
    container_name: mongors2
  mongors3:
    image: aupts2/mongodb:latest
    command: mongod --noprealloc --smallfiles --replSet rs1 --nojournal --oplogSize 16 --noauth --port 27017
    container_name: mongors3
  mongocfg1:
    image: aupts2/mongodb:latest
    command: mongod --noprealloc --smallfiles --configsvr --nojournal --oplogSize 16 --noauth --port 27017
    container_name: mongocfg1
    hostname: mongocfg1
  mongocfg2:
    image: aupts2/mongodb:latest
    command: mongod --noprealloc --smallfiles --configsvr --nojournal --oplogSize 16 --noauth --port 27017
    container_name: mongocfg2
    hostname: mongocfg2
  mongocfg3:
    image: aupts2/mongodb:latest
    command: mongod --noprealloc --smallfiles --configsvr --nojournal --oplogSize 16 --noauth --port 27017
    container_name: mongocfg3
    hostname: mongocfg3
  mongos1:
    image: aupts2/mongodb:latest
    command: mongos --configdb mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017
    container_name: mongos1
    ports:
    - "27017:27017"
    depends_on:
    - mongocfg1
    - mongocfg2
    - mongocfg3
